### PR TITLE
Create vaillant-pmw-configuration.json

### PR DESCRIPTION
**Pull request by dkuschmierz**
Configuration for PMW-W fresh water stations

### CODE REVIEW

**Review by csowada — COMMENTED** [review]
Great work, but could you please translate the file to english please.

**Comment by dkuschmierz** [comment]
I translated the file...

**Comment by csowada** [comment]
Short information, all configuration files will move in the next version to the ebus-configuration bundle.
So I will close this pull request and add it directly to the new bundle next days.

**Comment by csowada** [comment]
I close this request, I've added your files with this commit in the configuration bundle.
https://github.com/csowada/ebus-configuration/commit/21170a2b2bb1e0ea4465eb14b49675425b46b3a5

**Pull request closed without merging**
