### PR TITLE
Create vaillant-vr90-configuration.json

### PR DESCRIPTION
**Pull request by dkuschmierz**

### CODE REVIEW

**Review by csowada — COMMENTED** [review]
Great work, but could you translate your file to english. Thank you. And a valid public email address as author would be great.

**Comment by dkuschmierz** [comment]
OK, i updated the file to english. Would it be possible to introduce more label descriptions in the config files for a new version of the binding?

E.g.:
{"name": "temp_t1", "type": "data2c", "label": "Temperatur", "language":"german", "format":"%.1f°C"} 
{"name": "temp_t1", "type": "data2c", "label": "Temperatur", "language":"english", "format":"%.1f°C"}

**Comment by dkuschmierz** [comment]
Another advantage would be different factors for different countries...

**Comment by csowada** [comment]
I close this request, I've added your files with this commit in the configuration bundle.
https://github.com/csowada/ebus-configuration/commit/21170a2b2bb1e0ea4465eb14b49675425b46b3a5

**Pull request closed without merging**
